language: python
python:
  - "3.7"
services:
  - docker
# command to install dependencies
before_script: pip install docker-compose

script:
    - docker-compose run app sh -c "python manage.py" test && flake8"